# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:12.18.1
    steps:
      - checkout
      # Download and cache dependencies
      - run: cd PlanningPoker.Web/ && yarn install
      # build Vue App
      - run: cd PlanningPoker.Web/ && yarn build
      # run tests!
      # - run: cd PlanningPoker.Web/ && yarn test:unit
